name: 'Prevent file change'
description: 'Fail a pull request workflow if a certain file is changed'
author: 'Xavier Alvarez'
inputs:
  githubToken:
    required: true
    description: 'GitHub token'
  pattern:
    required: true
    description: 'JavaScript regular expression matching files which must not be changed'
runs:
  using: 'node12'
  main: 'dist/index.js'
