name: 'Prevent file change'
description: 'Fail a pull request workflow if certain files are changed'
author: 'Xavier Alvarez'
branding:
  icon: 'stop-circle'
  color: 'red'
inputs:
  githubToken:
    required: true
    description: 'GitHub token'
  pattern:
    required: true
    description: 'JavaScript regular expression matching files which must not be changed'
runs:
  using: 'node12'
  main: 'dist/index.js'
